os:
  - linux
language: java
before_install:
  - export LD_LIBRARY_PATH=$HOME/lib
  - ./travis-setup.sh
  - cd jblosc

install:
  - mvn install -B -V

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/lib