os:
  - linux
#  - osx
language: java
before_install: 
  - export LD_LIBRARY_PATH=/usr/local/lib
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - cd jblosc
  - git clone https://github.com/Blosc/c-blosc.git
  - cd c-blosc
  - rm -rf build
  - mkdir build
  - cd build
  - sudo cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
  - sudo cmake --build . --target install
  - cd ../..

install:
  - mvn install -B -V
